### ISSUE TITLE
Restarting WeeWX may cause spikes in data?

### ISSUE THREAD

**Issue by ArendPWS** [BobAtchley/weewx-ws6in1#4] opened 2020-09-01 18:22 UTC
This could be related to issues #2 and #3?

I noticed this for some time now, but could not work out what might be the cause. In the graph below there is a small spike just after midnight. This is the moment when a cronjob runs a script that stops WeeWX, downloads the contents of the console, checks the number of entries in memory, creates a backup of this console-data and then restarts WeeWX.
But there are also two big downward pointing temperature spikes. They must have occured when restarting WeeWX because of all the testing I did today. Until now I haven't been able to force the error(spikes) to occur with different configuration options (record_generation: hardware/software) and restarts. I am going to configure weewx.conf now with these settings:

[StdArchive]
record_generation = software (was hardware)
no_catchup = True (just found out today about this option)

And let it run for some time/days and will check if the spikes popup again at some point.

My configuration at the moment is:

Driver: WS6in1 0.8
WeeWX version: 4.1.1
Belchertown Skin Version: 1.2rc2

![temperatuur](https://user-images.githubusercontent.com/67259651/91890029-1b41d880-ec8f-11ea-9968-61cce58900ec.png)

**Comment by BobAtchley** [comment] 2020-09-01 18:45
I would say this is definitely related to issue #3.   The temperature is the temperature from 2 hours before due to the time difference between the console and the actual time

**Comment by BobAtchley** [comment] 2020-09-24 19:50
This was caused by the driver not taking into account local time when back filling and is now fixed (0.9).  There will still be a problem when Summer time ends/begins unless the local device is set not to use summertime.

**Closed as completed by BobAtchley** 2020-09-24 19:50 UTC
